### ISSUE TITLE
Using count with wrong data_type results in error

### ISSUE THREAD

**Issue by Eeleco** [PimDoos/MorgenWonenIoT#1]
Please specify data_type for the "count" option in modbus_climate.yaml

"count" can only be used with "data_type" `custom` or `string`. Default "data_type" is INT16 which results in an error.

Set datatype
`data_type: custom`

Set Python struct for unpacking
`structure: ">H"`

```
- name: EHST20D
  slave: 4
  address: 94
  target_temp_register: 54
  count: 1
  data_type: custom
  structure: ">H"
  precision: 1
  scale: 0.01
  max_temp: 25
  min_temp: 10
  temp_step: 0.5
  
- name: EHST20D Tank
  slave: 4
  address: 105
  target_temp_register: 30
  count: 1
  data_type: custom
  structure: ">H"
  precision: 1
  scale: 0.01
  max_temp: 55
  min_temp: 40
  temp_step: 0.5

```

**Comment by PimDoos** [comment]
Removed count from the configuration altogether, this parameter should not be needed anymore.
